apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-js-sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appd-test
    spec:
      containers:
      - name: appd-test
        image: kevinbappd/appdnodejspublic
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
