apiVersion: v1
kind: Service
metadata:
  name: node-js-sample
  labels:
    app: appd-test
spec:
  selector:
    app: appd-test
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
